In [3]:
import numpy as np 
x = np.array([1, 2, 3, 5])
N = 3
np.vander(x, N)



array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]])

In [4]:
np.column_stack([x**(N-1-i) for i in range(N)])


array([[ 1,  1,  1],
       [ 4,  2,  1],
       [ 9,  3,  1],
       [25,  5,  1]], dtype=int32)

In [8]:
x = np.array([1, 2, 3, 5])
np.vander(x)




np.vander(x, increasing=False)



array([[  1,   1,   1,   1],
       [  8,   4,   2,   1],
       [ 27,   9,   3,   1],
       [125,  25,   5,   1]])

In [9]:
np.linalg.det(np.vander(x))

(5-3)*(5-2)*(5-1)*(3-2)*(3-1)*(2-1)



48

In [6]:
np.linalg.det(np.vander(x))

(5-3)*(5-2)*(5-1)*(3-2)*(3-1)*(2-1)



48